### ISSUE TITLE
conda install not working

### ISSUE THREAD

**Issue by njbowen** [stracquadaniolab/baghera#6]
conda install -c stracquadaniolab -c bioconda -c conda-forge baghera

doesn't seem to function.

**Comment by violafanfani** [comment]
Hi @njbowen, 
I just tried on my laptop (linux) and it looks like the bioconda channel is forcing the wrong dependencies.
Can you try running `conda install -c stracquadaniolab -c conda-forge baghera`. I've also experience that using mamba often speeds up the installation of many dependencies (conda install mamba;mamba install -c stracquadaniolab -c conda-forge baghera).
If that doesn't work let me know what system are you working on and the error you are getting.
Have a nice day

**Comment by njbowen** [comment]
that fixed it, thanks so much.  btw, is there a pipeline listed for generating the 1146 hereditary cancer genes from the manuscript?  or is it a compilation of top genes from running on all of the data sets?  is there a table of those 1146 genes reported anywhere?  thanks, again.

**Comment by violafanfani** [comment]
Thanks fot your interest. All the results are on zenodo under 'Heritability analysis of the 38 cancers in the UK Biobank' (https://zenodo.org/record/3968269#.Yexay5FKhhE). 'UKBB_v2/normal_group_top16_significant.csv' should be what you are looking for. You will also find the single cancer results and (geneResults) and the characterisation tables. 
We also have a snakemake pipeline alongside the tool, but it will be quite time consuming to analyse all 38 cancer types. 
Let me know if you need more help,  otherwise I will go ahead and close this issue. 
Have a nice day

**Comment by njbowen** [comment]
Thanks, that's all, I closed the issue.  Have great day.
